### ISSUE TITLE
Template files are not digitally signed

### ISSUE THREAD

**Issue by furiousd** [zotero/zotero-word-for-windows-integration#21]
Because the template files (zotero.dot, zotero.dotm) have VB code in them, they trigger unsigned macro warnings when used in a Word installation that does not automatically trust all macros.  Since this is a huge security concern, many professional environments prevent this and only allow signed macros in Word.  Signing the VBA projects could allow such users to trust the signature, restoring seamless integration of Zotero into Word.

I have done this myself and confirmed that it worked (for me).  But obviously I can't sign these files for everyone who uses the plugin.

Solution: add a digital signature to the VBA project in each Word template file.

**Comment by penguinthingie** [comment]
Same issue here. There are forum posts claiming Zotero.dotm is digitally signed but if you look at the file, it does not have any such signatures and it is creating a huge security concern within enterprise systems like ours. Please add a digital signature to Zotero.dotm so this issue can be a relief for hundreds of others like us. Thank you for the great contribution to this product.

**Comment by dstillman** [comment]
The macros [have been signed](https://forums.zotero.org/discussion/comment/297905/#Comment_297905) since January 2018. There may be some other security restriction in your enterprise that restricts macros to specific publishers, but you'd have to talk to your IT department about that.

You can see the signature by opening the Visual Basic Editor, clicking on the Zotero project, and going to Tools → Digital Signature. (You might not be able to do this if you're unable to load the macros.) The plugin works fine for me with "Disable all macros except digitally signed macros" selected in Trust Center.

![signature1](https://user-images.githubusercontent.com/783082/62512653-da0a9b00-b7e6-11e9-949d-352764fd7c5b.png)

![signature2](https://user-images.githubusercontent.com/783082/62512654-dc6cf500-b7e6-11e9-94f2-3bf5ea698e6e.png)
