### ISSUE TITLE
Refresh button should update all citations if style has been updated in Zotero

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-word-for-windows-integration#34]
In #28 @rmzelle commented:

> Also, and this is tangentially related to what the label of the "Refresh" button should be, does clicking "Refresh" also reload the citation style? If not, can it be changed to do that?
>
> @adam3smith and others currently recommend users to switch to another style and back after updating a CSL style in Zotero, which isn't very obvious or quick (see e.g. https://forums.zotero.org/discussion/comment/212434/#Comment_212434). If the same could be achieved by clicking the "Refresh" button that seems much more straightforward.

I am not sure if we store enough information in the documents (last-modified timestamp would be required), but it would be good to have this.

**Comment by rmzelle** [comment]
> I am not sure if we store enough information in the documents (last-modified timestamp would be required), but it would be good to have this.

Do you have any performance metrics on how much time it costs to reload a style? If it's <1 s, maybe you can just always reload it without bothering for a check, at least for now.

**Comment by adomasven** [comment]
I do not, but I'm fairly appalled by Zotero performance with big documents as it is already, so avoiding to make it worse is a good plan.

**Comment by adam3smith** [comment]
I think Rintze is suggesting to reload it on Refresh specifically, not more generally. That button wouldn't be something users regularly use, so adding half a second there isn't very costly.

**Comment by rmzelle** [comment]
> I think Rintze is suggesting to reload it on Refresh specifically, not more generally.

Right. Checking a last-modified timestamp would of course be preferred, but maybe that's not worth waiting for if the performance penalty is minor.

Also, @adomasven, do you know what the current behavior around reloading styles in word processor documents is, by the way? I've always been a bit confused why it's necessary to switch styles and back to get Zotero to use the updated version of a reinstalled style. Styles aren't embedded in word documents, are they? Are they kept in memory or in the Zotero SQL database, and does that need flushing out?

**Comment by adomasven** [comment]
> I think Rintze is suggesting to reload it on Refresh specifically, not more generally. That button wouldn't be something users regularly use, so adding half a second there isn't very costly.

That's a good point. I don't think adding a last-modified timestamp is a big hassle though and on a second thought a full refresh could apply for citation inserts too.

> Also, @adomasven, do you know what the current behavior around reloading styles in word processor documents is, by the way?
A document style change causes every citation to be replaced. A normal refresh simply checks if any item data in Zotero has changed to update bibliography and citation text, and if citations have been removed/moved to update ibid/numbering.

**Comment by rmzelle** [comment]
(I'm also not totally clear on the exact use cases for clicking the "Refresh" button to begin with. I think I only use it when I make corrections to item metadata in Zotero, which needs a click on the button to pull in the changes. Deleting citation fields and having the bibliography update to reflect the deletion is probably another. Are they more cases?)

cc @fbennett

**Comment by rmzelle** [comment]
> A document style change causes every citation to be replaced. A normal refresh simply checks if any item data in Zotero has changed to update bibliography and citation text, and if citations have been removed/moved to update ibid/numbering.

Yes, I know. I meant to ask: is there currently any other trigger for updating the used CSL style, other than switching to another style and back in the document preferences? Would restarting Zotero and doing a full refresh in the word document (by clicking the Refresh button) also do it?

**Comment by adomasven** [comment]
> Yes, I know. I meant to ask: is there currently any other trigger for updating the used CSL style

Do you mean updating every zotero field text? Only changing the CSL style causes every field text to be updated. The document just stores the style ID and has no awareness of the fact that the CSL code has changed in Zotero database. Otherwise I am not sure what you have in mind by "updating the used CSL style".

**Comment by adam3smith** [comment]
I guess to ask this a different way, assume the following:
1. I start a document, cite a couple (citations A) of things using the Word add-on. Let's say for simplicity sake it's a numerical style: (1)
2. The citation style I use in that document is updated (either automatically or by me) to use square brackets [1].
3. I cite some more things (citations B) in that same document

I think what Rintze and I are not clear on is when citations A and citations B switch from (1) to [1].

**Comment by rmzelle** [comment]
> Only changing the CSL style causes every field text to be updated.

Clicking the "Refresh" button doesn't?

> Otherwise I am not sure what you have in mind by "updating the used CSL style".

Say you have v1 of CSL style A installed, and you create a Word document with that style. You then install v2 of that same style. How can I then make Zotero use v2 in the existing Word document? Is switching styles really the only option? Or would e.g. restarting Zotero and clicking Refresh work as well? (since the Word document doesn't embed the used CSL style, I'm just confused why Zotero is even able to continue to use v1 after the user installs v2, and why clicking the Refresh button currently doesn't suffice for having Zotero switch from v1 to v2)

**Comment by adomasven** [comment]
Right. Sorry for failing to get this. I have not dug around enough in the code, to confirm this, so this might be wrong/incomplete, but from what I know: 

Zotero stores document sessions in memory for every document that communicates to it, along with an instance of citeproc, initialised with the CSL style code as it is upon first communication. Subsequent communications do not cause the citeproc instance (and thus CSL code) to be reinitialized. Restarting Zotero clears the document sessions from memory. A new communication request from the document after Zotero restart would cause an instantiation of a document session and citeproc with whatever is the current version of CSL style code.

This is where my current knowledge ends, but following this logic would mean that restarting Zotero and pressing Refresh should have the same effect as switching the styles back and forth (which also causes citeproc reinitialization).

Which also means, that the better way to address this is to update document sessions upon style updates, rather than keeping timestamps. I will have to dig around this some more. Sorry for not having better answers for now.

**Comment by adam3smith** [comment]
That's actually super helpful in understanding what's going on. Thanks!

**Comment by fbennett** [comment]
I've often thought the switch-out-switch-back tango is a headache, and it's awkward to explain to users in support.

Automatic refresh immediately on the reinstall might be awkward, since you would need a navigate into all live sessions somehow. I don't know if that's even possible, and users might be alarmed at Refresh triggering implicitly in open documents after a style update (which might happen in background).

Rather than a timestamp, would it do to set an md5 checksum of the style source?

**Comment by dstillman** [comment]
I don't think @adomasven was suggesting automatic document refresh on style update, just an update of the citeproc instance in the session with the new style so that the next refresh in the document would reflect the change, which I think is the behavior we're going for. Not sure if there'd be unexpected problems with new citations from an updated style without a full refresh. If so we'd need to set a flag on the session to trigger a document refresh at the next insert.

I don't think we need to store any new metadata in the document to support this.

**Comment by fbennett** [comment]
<blockquote>I don't think @adomasven was suggesting automatic document refresh on style update</blockquote>Yes, sorry, I was thinking out loud there.

**Comment by rmzelle** [comment]
> Not sure if there'd be unexpected problems with new citations from an updated style without a full refresh. If so we'd need to set a flag on the session to trigger a document refresh at the next insert.

Styles might change considerable (e.g. from author-date to numeric), or e.g. disambiguation settings might change, so a full document refresh seems best upon a style update. That said, doesn't a document refresh take several minutes for some people with a very large bibliography? It could result in unexpected freezes if Zotero silently updates a style in the background, and the user then inserts a new citation in their big document, triggering a full document refresh

**Comment by adomasven** [comment]
> Styles might change considerable (e.g. from author-date to numeric), or e.g. disambiguation settings might change, so a full document refresh seems best upon a style update.

Every citation insert causes a full crawl of the document to check for ibid/numbering updates. From my initial measurement most of that time is spent in citeproc-js, so adding an extra write for every citation is marginal. However, re performance improvement for big bibliographies see [my thread on the forums](https://forums.zotero.org/discussion/64960/feature-suggestion-delay-updating-citations-in-documents#latest)

**Comment by JohnLukeBentley** [comment]
I'm unclear why this thread was closed.

A quick method of updating MS Word citation formats if the underlying CSL is changed, without "the switch-out-switch-back tango", would be a great thing. If this can't be incorporated into the existing [Refresh] button, because of performance penalties, how about a separate [Refresh CSL] button?

**Comment by dstillman** [comment]
It was closed by a commit that implemented it.

**Comment by JohnLukeBentley** [comment]
It's not happening at my end.

What I do:
* Open Zotero Standalone.
* Open MS Word with a document having Zotero Citations.
* Make a change in my underlying custom *.csl in a standalone text editor.
* MS Word > |Zotero| > [Refresh].
* The change to the *.csl does not come through.

However, if I use  MS Word > |Zotero| > [Document Preferences] to switch to another style, then back to the style of interest, the change does come through.

I'm on Zotero 5.0.47.

**Comment by dstillman** [comment]
Right, that's different, and not related to word processor integration. The change here was to force document citation regeneration when the style is updated in Zotero (e.g., after pulling an update from the repo, as in the linked forum thread). If you're just editing a CSL file on disk, the style isn't being updated in Zotero.

But you shouldn't really edit files in the 'styles' directory anyway. A better approach would be to have your development copy of the CSL file elsewhere on disk (where, among other things, it wouldn't be affected by a style reset while debugging a problem) and just double-click it after making changes to reinstall it in Zotero. That should then trigger the new behavior here.

**Comment by JohnLukeBentley** [comment]
Thanks for correcting my misunderstanding.

> But you shouldn't really edit files in the 'styles' directory anyway. A better approach would be to have your development copy of the CSL file elsewhere on disk (where, among other things, it wouldn't be affected by a style reset while debugging a problem)

Thanks, that sorts me out on a number of fronts then.

So I tried your suggested procedure:
* Copied my style to a dev directory.
* Made a change.
* Doubled clicked the file in Windows Explorer.
* With Zotero Standalone already open, received the "Update existing style ..." dialog. Clicked [Install]
* MS Word > |Zotero| > [Refresh].
* I get an error:

> Zotero experienced an error updating your document.
>
> CSL error
> TypeError: this.registry.citationreg.citationById[c[0]] is undefined
> citationID=6aYkbZ4U
> noteIndex=0
> at array citationsPost index 0, from citation at document position 0

I've rebooted my machine and reproduced the bug. My CSL file validates at https://validator.citationstyles.org/.

I hope that reveals a genuine bug rather than turning this into a mere support thread.

**Comment by adomasven** [comment]
@JohnLukeBentley I cannot reproduce what you are describing above. Nor is this the right issue to be discussing this under, if it is indeed a new bug. Could you post in [zotero-dev](https://groups.google.com/forum/#!forum/zotero-dev) mailing list and produce a [Debug ID](https://www.zotero.org/support/debug_output):

1. Insert a citation in a new doc
2. Update the style and install it into Zotero
3. Click refresh and produce the error you described above
4. Submit a Debug ID and post it along with your post to zotero-dev.

**Comment by JohnLukeBentley** [comment]
Thanks  @adomasven. This turned out to be some kind of corruption of Zotero citation in MS Word codes, in my existing document (your mentioning to try this with a fresh doc was the relevant clue). Deleting all these citations in that document has gotten rid of the problem. If it emerges again I'll follow your procedure to post in zotero-dev.
