### ISSUE TITLE
Show clear error when Word Startup folder is set to Zotero application directory

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-word-for-windows-integration#60]
E.g., https://forums.zotero.org/discussion/85801/error-1527566911-plug-in-wont-install

People seem to do this a lot. I've updated our instructions a lot to try to prevent this, but I've seen some [third-party documentation](https://forums.zotero.org/discussion/comment/366295/#Comment_366295) that's less clear. If people have done this, we should detect it at plugin installation time and show an alert explaining how to fix it (or maybe linking to a KB page).

**Comment by adomasven** [comment]
Do we cancel the installation of the plugin then? What text do we put in the alert?

**Comment by dstillman** [comment]
Yes, we should definitely cancel. No point in trying to install there — it will fail or do something weird like delete the file.

I can tweak the text.

**Comment by adomasven** [comment]
Strings commit here https://github.com/zotero/zotero/commit/3a684308cd6d37e24962a692e2e4cdc42aeaf284

Since Word stores a different startup folder location for each version of Word, we still install for startup locations that are valid and display a different error message than for those setups where all (or the only) startup locations are set in Program Files. Perhaps we should consider a separate wiki page for this.
